Repository DentiioApp/dentiio-front, pull requests merged in 2020-09, with the labels that each got.

#70 fix yarn lock security dependancy bit
  yarn.lock
Labels: dependencies

#72 Lory fix register
  src/App.js
  src/components/App/CaseItem/CaseItem.js
  src/components/App/DetailCase/PatientDetail.js
  src/components/App/Register/Register.js
  src/components/UI/Icon/Profile/iconProfile.js
  src/components/UI/Icon/iconNotifSubject/iconNotifSubject.js
  src/config/index.js
  src/containers/Home/Home.js
  src/services/Users.js
  src/store/actions/index.js
  src/store/reducers/cases.js
Labels: bug, toMerge

#73 upgrade dependencies
  .github/workflows/linter.yml
  package.json
  yarn.lock
Labels: dependencies, toMerge

#76 Button add case feature
  src/components/App/CaseItem/CaseItem.js
  src/components/App/Header/Header.js
  src/components/UI/Icon/Header/add.js
  src/components/UI/Icon/Header/notification.js
  src/components/UI/buttons/favButton.js
  src/containers/CasePost/CasePost.js
  src/containers/Cases/Cases.js
  src/containers/QuestionPost/QuestionPost.js
  src/index.js
Labels: good first issue, toMerge

#80 Data in case item
  src/components/App/CaseItem/CaseItem.js
  src/components/App/CaseItem/caseItem.scss
  src/components/App/Modal/ModalGuidelines-PostCase/ModalGuidelinesPostCase.js
  src/components/UI/Keywords/keywords.js
  src/containers/CasePost/CasePost.js
  src/containers/Landing-Page/LandingPage.js
  src/containers/Landing-Page/LandingPage.scss
  src/containers/Profile/Profile.js
Labels: Design, toMerge

#35 Afficher formulaire de validation de carte
  package.json
  src/App.js
  src/App.test.js
  src/components/App/CaseItem/CaseItem.js
  src/components/App/DetailCase/PatientDetail.js
  src/components/App/Header/Header.js
  src/components/App/Modal/ModalGuidelines-PostCase/ModalGuidelinesPostCase.js
  src/components/App/Register/Register.js
  src/components/App/SignIn/SignIn.js
  src/components/App/Status/Status.js
  src/components/App/Status/status.scss
  src/components/App/StatusForm/StatusForm.js
  src/components/App/StatusModal/StatusModal.js
  src/components/ResponsiveDesign/AuthStyle.js
  src/components/UI/Icon/Header/add.js
  src/components/UI/Icon/Header/notification.js
  src/components/UI/Icon/Profile/iconProfile.js
  src/components/UI/Icon/iconNotifSubject/iconNotifSubject.js
  src/components/UI/buttons/favButton.js
  src/config/index.js
  src/containers/CasePost/CasePost.js
  src/containers/Cases/Cases.js
  src/containers/DetailCase/DetailCase.js
  src/containers/Home/Home.js
  src/containers/Profile/Profile.js
  src/containers/QuestionPost/QuestionPost.js
  src/index.js
  src/services/Auth.js
  src/services/Cases.js
  src/services/Patient.js
  src/services/SaveCard.js
  src/services/Users.js
  src/store/actions/Auth.js
  src/store/actions/Cases.js
  src/store/actions/index.js
  src/store/reducers/cases.js
  src/store/reducers/home.js
  src/store/reducers/index.js
  src/store/reducers/user.js
  yarn.lock
Labels: toImprove, toMerge

#81 create template to add case.ADD CASE IS FUNCTIONNAL
  src/containers/CasePost/CasePost.js
  src/services/Cases.js
Labels: enhancement, toMerge

#78 Mounia search bar
  package.json
  src/App.js
  src/components/App/CaseItem/CaseItem.js
  src/components/App/CasesList/CasesList.js
  src/components/App/DetailCase/NavbarDetail.js
  src/components/App/Search/Search.js
  src/components/App/Search/Search.scss
  src/components/App/Status/Status.js
  src/config/index.js
  src/containers/Cases/Cases.js
  src/services/Home.js
  src/store/actions/index.js
  src/store/reducers/cases.js
  src/store/reducers/home.js
  src/store/reducers/user.js
  src/variables.scss
  yarn.lock
Labels: enhancement, help wanted

#84 fiche patient to improve
  src/components/App/ClinicCase/ClinicCase.js
  src/components/App/ClinicCase/clinicCase.scss
  src/components/App/Conclusion/Conclusion.js
  src/components/App/Conclusion/conclusion.scss
  src/components/App/Diagnostic/Diagnostic.js
  src/components/App/Diagnostic/diagnostic.scss
  src/components/App/Evolution/Evolution.js
  src/components/App/Evolution/evolution.scss
  src/components/App/Exam/Exam.js
  src/components/App/Exam/exam.scss
  src/components/App/Patient/Patient.js
  src/components/App/Patient/patient.scss
  src/components/App/Register/Register.js
  src/components/App/Search/Search.js
  src/components/App/TreatPlan/TreatPlan.js
  src/components/App/TreatPlan/treatPlan.scss
  src/config/index.js
  src/containers/CasePost/CasePost.js
  src/services/Cases.js
  src/services/Home.js
  src/services/Patient.js
  src/store/actions/index.js
  src/store/reducers/cases.js
  src/store/reducers/home.js
Labels: enhancement

#87 add var page to clical case , add label to age in create case
  src/components/App/Patient/Patient.js
  src/services/Cases.js
Labels: toImprove, toMerge

#91 Lory improve add case
  src/components/App/CasesList/CasesList.js
  src/components/App/ClinicCase/ClinicCase.js
  src/components/App/Conclusion/Conclusion.js
  src/components/App/Diagnostic/Diagnostic.js
  src/components/App/Evolution/Evolution.js
  src/components/App/Exam/Exam.js
  src/components/App/Patient/Patient.js
  src/components/App/TreatPlan/TreatPlan.js
  src/components/UI/Paginator/Paginator.js
  src/config/index.js
  src/containers/CasePost/CasePost.js
  src/services/Cases.js
  src/services/Patient.js
  src/store/actions/Auth.js
  src/store/actions/index.js
Labels: toMerge

#92 Ajouter des cas en favoris
  package.json
  src/components/App/CaseItem/CaseItem.js
  src/components/App/CasesList/CasesList.js
  src/components/App/DetailCase/CardPlanTreatment.js
  src/components/App/Header/Header.js
  src/components/App/SignIn/SignIn.js
  src/components/UI/Paginator/Paginator.js
  src/components/UI/buttons/favButton.js
  src/containers/CasePost/CasePost.js
  src/services/Cases.js
  src/store/actions/Cases.js
  src/store/actions/index.js
  src/store/reducers/cases.js
  yarn.lock
Labels: enhancement, toMerge

#95 Connect data detail case
  src/components/App/CaseItem/CaseItem.js
  src/components/App/DetailCase/NavbarDetail.js
  src/components/App/DetailCase/PatientDetail.js
  src/components/UI/Gallery/LightboxButton.js
  src/components/UI/Icon/Header/Add.js
  src/containers/DetailCase/DetailCase.js
  src/containers/DetailCase/detailCase.scss
  src/services/Cases.js
  yarn.lock
Labels: toMerge

#96 resolve warning
  src/containers/DetailCase/DetailCase.js
Labels: toMerge

#97 Lory fix redux error
  src/components/App/SideBarMenu/sideBarMenu.js
  src/components/UI/Paginator/Paginator.js
  src/services/Cases.js
Labels: bug, toMerge

#98 comment devtools
  src/index.js
Labels: bug, toMerge

#100 add id to redux
  src/services/Auth.js
  src/store/reducers/user.js
Labels: enhancement

#93 Sidebar menu
  src/components/App/Header/Header.js
  src/components/App/SideBarMenu/sideBarMenu.js
  src/index.js
  src/services/Pathologies.js
  src/store/actions/Pathologies.js
  src/store/actions/index.js
  src/store/reducers/cases.js
  src/store/reducers/index.js
  src/store/reducers/pathologies.js
  src/store/reducers/user.js
Labels: enhancement, toImprove

#101 Design login and register in index
  src/components/App/Header/Header.js
  src/components/App/Register/Register.js
  src/components/App/SignIn/SignIn.js
  src/components/ResponsiveDesign/AuthStyle.js
  src/index.js
  src/serviceWorker.js
  src/store/actions/index.js
Labels: toMerge

#103 Lory show favorite
  src/components/App/CaseItem/CaseItem.js
  src/components/App/CasesList/CasesList.js
  src/components/App/ClinicCase/ClinicCase.js
  src/components/App/Conclusion/Conclusion.js
  src/components/App/DetailCase/NavbarDetail.js
  src/components/App/DetailCase/PatientDetail.js
  src/components/App/Diagnostic/Diagnostic.js
  src/components/App/Evolution/Evolution.js
  src/components/App/Exam/Exam.js
  src/components/App/Header/Header.js
  src/components/App/Patient/Patient.js
  src/components/App/Search/Search.js
  src/components/App/SideBarMenu/sideBarMenu.js
  src/components/App/SignIn/SignIn.js
  src/components/App/TreatPlan/TreatPlan.js
  src/components/UI/Paginator/Paginator.js
  src/components/UI/RightMenuIcon/rightMenuIcon.js
  src/components/UI/buttons/favButton.js
  src/config/index.js
  src/containers/CasePost/CasePost.js
  src/containers/Cases/Cases.js
  src/containers/DetailCase/DetailCase.js
  src/containers/Favorites/Favorites.js
  src/index.js
  src/serviceWorker.js
  src/services/Cases.js
  src/services/Pathologies.js
  src/services/Patient.js
  src/services/Specialities.js
  src/services/Treatments.js
  src/services/Users.js
  src/store/actions/Auth.js
  src/store/actions/Cases.js
  src/store/actions/Pathologies.js
  src/store/actions/Specialities.js
  src/store/actions/Treatments.js
  src/store/actions/index.js
  src/store/reducers/cases.js
  src/store/reducers/index.js
  src/store/reducers/pathologies.js
  src/store/reducers/specialities.js
  src/store/reducers/treatments.js
Labels: Design, bug, toMerge

#104 Profile connect to data
  src/components/App/CaseItem/caseItem.scss
  src/components/App/CasesList/CasesList.js
  src/components/App/Header/Header.js
  src/containers/Profile/Profile.js
  src/images/profile.png
  src/serviceWorker.js
  src/services/Cases.js
  src/services/Users.js
Labels: toMerge

#105 Ajouter un loader a la page cases
  src/components/App/CasesList/CasesList.js
  src/images/Spinner-1s-347px.svg
Labels: Design, enhancement, toMerge

#106 Add mailing in front, change bouton for create case process , link su…
  src/components/App/CaseItem/CaseItem.js
  src/components/App/CasesList/CasesList.js
  src/components/App/ClinicCase/ClinicCase.js
  src/components/App/Conclusion/Conclusion.js
  src/components/App/Diagnostic/Diagnostic.js
  src/components/App/Evolution/Evolution.js
  src/components/App/Exam/Exam.js
  src/components/App/Header/Header.js
  src/components/App/Patient/Patient.js
  src/components/App/Register/Register.js
  src/components/App/SideBarMenu/sideBarMenu.js
  src/components/App/SignIn/SignIn.js
  src/components/App/TreatPlan/TreatPlan.js
  src/components/UI/buttons/favButton.js
  src/components/UI/titleHeader/TitleHeader.js
  src/containers/Profile/Profile.js
  src/index.js
  src/services/Cases.js
  src/services/Email.js
  src/services/Users.js
  src/store/reducers/home.js
Labels: Design, enhancement, toMerge

#108 require cgu in register
  src/components/App/Register/Register.js
Labels: enhancement, toMerge

#110 add random text to pseudo , remove pseudo in subscribbe, ask mail in …
  package.json
  src/components/App/Register/Register.js
  src/components/App/SignIn/SignIn.js
  src/components/UI/buttons/GradientBtn.js
  src/config/index.js
  src/index.js
  src/services/Users.js
  yarn.lock
Labels: enhancement, toMerge

#111 base 64 is kept
  src/components/App/Register/Register.js
  src/components/App/SignIn/SignIn.js
  src/components/App/Status/Status.js
  src/containers/Favorites/Favorites.js
  src/containers/Home/Home.js
  src/services/SaveCard.js
  src/services/Users.js
  src/store/actions/Auth.js
  src/store/actions/index.js
  src/store/reducers/user.js
Labels: enhancement, toMerge

#112 comment add cps process
  src/components/App/SignIn/SignIn.js
  src/components/App/Status/Status.js
  src/services/Users.js
Labels: bug, toMerge
