Repository DentiioApp/dentiio-front, pull requests merged in 2020-07, with the labels that each got.

#64 fctorse api call and fetch
  src/App.js
  src/App.test.js
  src/components/App/CaseItem/CaseItem.js
  src/components/App/CasesList/CasesList.js
  src/components/App/Header/Header.js
  src/components/App/Register/Register.js
  src/components/App/SignIn/SignIn.js
  src/components/App/header/Header.js
  src/config/index.js
  src/containers/Cases/Cases.js
  src/containers/DetailCase/DetailCase.js
  src/containers/Home/Home.js
  src/index.js
  src/services/Cases.js
  src/services/Users.js
  src/store/actions/addFav.js
  src/store/actions/index.js
  src/store/actions/registerUser.js
  src/store/reducers/cases.js
  src/store/reducers/home.js
  src/store/reducers/user.js
  yarn.lock
Labels: toMerge

#68 Timeout notification
  src/components/App/SignIn/SignIn.js
  src/index.js
Labels: enhancement, good first issue, toMerge

#66 FIx bug mobile register
  src/components/ResponsiveDesign/AuthStyle.js
  src/images/logo.svg
Labels: bug, toMerge
