Repository DentiioApp/dentiio-front, pull requests merged in 2020-10, with the labels that each got.

#121 Design romain
  public/assets/apple-icon-120.jpg
  public/assets/apple-icon-152.jpg
  public/assets/apple-icon-167.jpg
  public/assets/apple-icon-180.jpg
  public/assets/apple-splash-1080-1920.jpg
  public/assets/apple-splash-1125-2436.jpg
  public/assets/apple-splash-1136-640.jpg
  public/assets/apple-splash-1242-2688.jpg
  public/assets/apple-splash-1334-750.jpg
  public/assets/apple-splash-1536-2048.jpg
  public/assets/apple-splash-1620-2160.jpg
  public/assets/apple-splash-1668-2224.jpg
  public/assets/apple-splash-1668-2388.jpg
  public/assets/apple-splash-1792-828.jpg
  public/assets/apple-splash-1920-1080.jpg
  public/assets/apple-splash-2048-1536.jpg
  public/assets/apple-splash-2048-2732.jpg
  public/assets/apple-splash-2160-1620.jpg
  public/assets/apple-splash-2224-1668.jpg
  public/assets/apple-splash-2388-1668.jpg
  public/assets/apple-splash-2436-1125.jpg
  public/assets/apple-splash-2688-1242.jpg
  public/assets/apple-splash-2732-2048.jpg
  public/assets/apple-splash-640-1136.jpg
  public/assets/apple-splash-750-1334.jpg
  public/assets/apple-splash-828-1792.jpg
  public/assets/manifest-icon-192.png
  public/assets/manifest-icon-512.png
  public/index.html
  public/manifest.json
  src/components/App/Register/Register.js
  src/components/App/Register/register.scss
  src/components/App/Search/Search.js
  src/components/App/Search/Search.scss
  src/components/App/SideBarMenu/sideBarMenu.js
  src/components/App/SignIn/SignIn.js
  src/components/App/Status/Status.js
  src/components/ResponsiveDesign/AuthStyle.js
  src/components/UI/Dawers/CategorieCases.scss
  src/components/UI/Dawers/CategoriesCases.js
  src/components/UI/Modal/StatusJustif.js
  src/components/UI/buttons/GradientBtn.js
  src/components/UI/buttons/favButton.js
  src/containers/Cases/Cases.js
  src/containers/Favorites/Favorites.js
  src/containers/Home/Home.js
  src/services/CatPathologies.js
  src/services/Pathologies.js
  src/store/actions/CatPathologies.js
  src/store/actions/index.js
  src/store/reducers/catPathologies.js
  src/store/reducers/home.js
  src/store/reducers/index.js
Labels: Design, toMerge

#117 Lory some improves
  src/components/App/CasesList/CasesList.js
  src/components/App/ClinicCase/ClinicCase.js
  src/components/App/Conclusion/Conclusion.js
  src/components/App/Diagnostic/Diagnostic.js
  src/components/App/Evolution/Evolution.js
  src/components/App/Exam/Exam.js
  src/components/App/Patient/Patient.js
  src/components/App/Register/Register.js
  src/components/App/Search/Search.js
  src/components/App/SignIn/SignIn.js
  src/components/App/Status/Status.js
  src/components/App/TreatPlan/TreatPlan.js
  src/components/ResponsiveDesign/AuthStyle.js
  src/components/UI/Dawers/CategoriesCases.js
  src/components/UI/Dawers/Spinner.js
  src/components/UI/Modal/StatusJustif.js
  src/components/UI/buttons/GradientBtn.js
  src/config/index.js
  src/containers/CasePost/CasePost.js
  src/containers/Home/Home.js
  src/services/Cases.js
  src/services/Pathologies.js
  src/services/Patient.js
  src/services/Users.js
  src/store/actions/index.js
  src/store/reducers/home.js
  src/store/reducers/user.js
Labels: enhancement, toMerge

#123 Page favorite
  src/components/App/Patient/Patient.js
  src/containers/Favorites/Favorites.js
  src/services/Cases.js
Labels: enhancement, toMerge

#124 Factorise le code
  src/components/App/CasesList/CasesList.js
  src/components/App/ClinicCase/ClinicCase.js
  src/components/App/Register/Register.js
  src/components/App/Search/Search.js
  src/components/App/SignIn/SignIn.js
  src/components/App/Status/Status.js
  src/components/UI/buttons/favButton.js
  src/containers/CasePost/CasePost.js
  src/containers/Cases/Cases.js
  src/containers/DetailCase/DetailCase.js
  src/containers/Favorites/Favorites.js
  src/containers/Home/Home.js
  src/containers/Profile/Profile.js
  src/index.js
  src/services/Home.js
  src/services/Jobs.js
  src/services/Users.js
  src/store/actions/Cases.js
  src/store/actions/index.js
  src/store/reducers/cases.js
  src/store/reducers/home.js
  src/utils/api/api.js
  src/utils/index.js
  yarn.lock
Labels: good first issue, toMerge

#125 Lory factorise code
  src/containers/DetailCase/DetailCase.js
  src/containers/Favorites/Favorites.js
  src/containers/Profile/Profile.js
Labels: duplicate

#126 Avatar user
  package.json
  src/components/App/CaseItem/CaseItem.js
  src/components/App/Header/Header.js
  src/components/UI/Avatars/Library.js
  src/components/UI/Avatars/UserAvatar.js
  src/components/UI/RightMenuIcon/rightMenuIcon.js
  src/config/index.js
  src/containers/Profile/Profile.js
  src/containers/UserAvatar/Tab.js
  src/containers/UserAvatar/UserAvatar.js
  src/index.js
  src/services/Users.js
  src/store/actions/index.js
  yarn.lock
Labels: toMerge

#129 Lory add spinner evrywhere with some fixes
  src/components/App/ClinicCase/ClinicCase.js
  src/components/App/Conclusion/Conclusion.js
  src/components/App/Diagnostic/Diagnostic.js
  src/components/App/Evolution/Evolution.js
  src/components/App/Exam/Exam.js
  src/components/App/Header/Header.js
  src/components/App/Patient/Patient.js
  src/components/App/Search/Search.js
  src/components/App/SignIn/SignIn.js
  src/components/App/TreatPlan/TreatPlan.js
  src/components/UI/buttons/favButton.js
  src/config/index.js
  src/containers/Cases/Cases.js
  src/containers/Favorites/Favorites.js
  src/containers/Home/Home.js
  src/index.js
  src/services/Patient.js
  src/services/Users.js
  src/store/actions/index.js
  src/store/reducers/cases.js
  src/store/reducers/home.js
  src/store/reducers/user.js
Labels: enhancement, toMerge

#131 Update account
  src/components/App/Header/Header.js
  src/components/UI/Dawers/Spinner.js
  src/components/UI/RightMenuIcon/rightMenuIcon.js
  src/components/UI/buttons/ParametersProfileButton.js
  src/config/index.js
  src/containers/Profile/EditProfile.js
  src/containers/Profile/Profile.js
  src/containers/UserAvatar/Tab.js
  src/index.js
  src/services/Users.js
  src/store/reducers/cases.js
Labels: toMerge

#132 Note case design
  src/components/App/CaseItem/CaseItem.js
  src/components/App/DetailCase/Rating.js
  src/containers/DetailCase/DetailCase.js
  src/containers/Profile/EditProfile.js
  src/containers/UserAvatar/Tab.js
Labels: Design, toMerge

#142 Design post case
  package.json
  src/components/App/Cases/ClinicCase/ClinicCase.js
  src/components/App/Cases/Conclusion/Conclusion.js
  src/components/App/Cases/Exam/Exam.js
  src/components/App/Cases/Patient/Patient.js
  src/components/App/Cases/PostCase/ClinicCase/ClinicCase.js
  src/components/App/Cases/PostCase/ClinicCase/clinicCase.scss
  src/components/App/Cases/PostCase/Conclusion/Conclusion.js
  src/components/App/Cases/PostCase/Conclusion/conclusion.scss
  src/components/App/Cases/PostCase/Diagnostic/Diagnostic.js
  src/components/App/Cases/PostCase/Diagnostic/diagnostic.scss
  src/components/App/Cases/PostCase/Evolution/Evolution.js
  src/components/App/Cases/PostCase/Evolution/evolution.scss
  src/components/App/Cases/PostCase/Exam/Exam.js
  src/components/App/Cases/PostCase/Exam/ExamComplementaire.js
  src/components/App/Cases/PostCase/Exam/exam.scss
  src/components/App/Cases/PostCase/Patient/Patient.js
  src/components/App/Cases/PostCase/Patient/patient.scss
  src/components/App/Cases/PostCase/TreatPlan/TreatPlan.js
  src/components/App/Cases/PostCase/TreatPlan/treatPlan.scss
  src/components/App/Cases/TreatPlan/TreatPlan.js
  src/components/UI/ResponsiveDesign/AuthStyle.js
  src/components/UI/Steppers/PostCaseStepper.js
  src/config/index.js
  src/containers/CasePost/CasePost.js
  src/store/actions/index.js
  src/store/reducers/homeReducer.js
  yarn.lock
Labels: Design, UX, toMerge

#143 CI CLEAN
  .circleci/config.yml
  .github/old_workflow/deploy-preprod.yml
  .github/old_workflow/sonar.yml
  .github/old_workflow/test.yml
  .github/workflows/deploy-preprod.yml
  README.md
  package.json
  sonar-project.properties
  src/components/App/Cases/CasesList/CasesList.js
  src/components/App/Cases/PostCase/ClinicCase/ClinicCase.js
  src/components/UI/Icon/Header/notification.js
  src/components/UI/Steppers/PostCaseStepper.js
  src/components/UI/buttons/FavButton/FavButton.js
  src/components/UI/buttons/Keywords/keywords.js
  src/containers/Cases/Cases.js
  src/containers/UserAvatar/Tab.js
Labels: CI / CD, toMerge

#147 Upgrade node-sasse
  package.json
  src/components/App/Cases/CasesList/CasesList.js
  yarn.lock
Labels: dependencies, toMerge
