Repository DentiioApp/dentiio-front, pull requests merged in 2020-05, with the labels that each got.

#19 Lory home cases
  src/components/App/Header/header.js
  src/components/App/Register/register.js
  src/components/App/SignIn/signIn.js
  src/containers/Cases/cases.js
  src/services/Auth.js
  src/services/CaseList.js
  src/services/LoginCheck.js
  src/store/actions/logUser.js
  src/store/reducers/log.js
  yarn.lock
Labels: toMerge

#21 Fix after move repo
  src/components/App/Register/register.js
  src/components/App/SignIn/signIn.js
  src/components/UI/buttons/GradientBtn.js
  src/services/Auth.js
  src/services/LoginCheck.js
  src/services/RegisterCheck.js
  src/store/reducers/log.js
  src/utils/Auth/index.js
  src/utils/index.js
Labels: bug, toMerge

#20 Component navbar romain
  src/components/App/Header/header.js
  src/components/Icon/Header/favorites.js
  src/components/Icon/Header/home.js
  src/components/Icon/Header/notification.js
  src/components/Icon/Header/profile.js
  src/components/UI/colorTheme/colorTheme.js
  src/components/UI/titleHeader/titleHeader.scss
  src/containers/Cases/cases.js
  src/containers/Favorites/favorites.js
  src/containers/Profile/profile.js
  src/index.js
Labels: enhancement, good first issue, toMerge

#28 Navbar mobile romain
  src/components/App/Case/case.js
  src/components/App/Header/header.js
  src/components/Icon/Header/favorites.js
  src/components/Icon/Header/home.js
  src/components/Icon/Header/notification.js
  src/components/Icon/Header/profile.js
  src/components/UI/colorTheme/colorTheme.js
  src/components/UI/colorTheme/palette.js
  src/components/UI/titleHeader/titleHeader.scss
  src/components/UI/titleHeader/titleHeaderMobile.js
  src/containers/Cases/cases.js
  src/containers/Favorites/favorites.js
  src/containers/Profile/profile.js
  src/images/titleHeaderMobile.svg
Labels: enhancement, toMerge

#23 Lory dentist status
  src/components/App/CardForm/cardForm.js
  src/components/App/Case/case.js
  src/components/App/CasesList/casesList.js
  src/components/App/Header/header.js
  src/components/App/Register/register.js
  src/components/App/SignIn/signIn.js
  src/components/App/StatusForm/statusForm.js
  src/components/App/StatusModal/statusModal.js
  src/components/Icon/Header/favorites.js
  src/components/Icon/Header/home.js
  src/components/Icon/Header/notification.js
  src/components/Icon/Header/profile.js
  src/components/UI/Icon/Header/favorites.js
  src/components/UI/Icon/Header/home.js
  src/components/UI/Icon/Header/notification.js
  src/components/UI/Icon/Header/profile.js
  src/components/UI/colorTheme/colorTheme.js
  src/components/UI/colorTheme/palette.js
  src/components/UI/favButton/FavButton.js
  src/components/UI/homeButton/HomeButton.js
  src/components/UI/homeButton/HomeButton.scss
  src/components/UI/profileImage/ProfileImage.js
  src/components/UI/titleHeader/titleHeaderMobile.js
  src/containers/Cases/cases.js
  src/containers/Favorites/favorites.js
  src/containers/Home/Home.js
  src/containers/Profile/profile.js
  src/index.js
  src/services/Auth.js
  src/services/RegisterCheck.js
  src/services/SaveCard.js
  src/services/css/registerStyle.js
  src/store/actions/cardCheck.js
  src/store/actions/cardSave.js
  src/store/actions/getCases.js
  src/store/actions/index.js
  src/store/actions/logUser.js
  src/store/actions/registerUser.js
  src/store/reducers/home.js
  src/store/reducers/index.js
  src/store/reducers/user.js
  src/utils/Auth/existEmail.js
  src/utils/cases/notes.js
  src/utils/fields/checkEmail.js
  src/utils/fields/checkFiles.js
  src/utils/fields/checkPassword.js
  src/utils/fields/checkText.js
  src/utils/index.js
  yarn.lock
Labels: good first issue, toMerge
