Repository DentiioApp/dentiio-front, pull requests merged in 2020-06, with the labels that each got.

#38 Lory scale form
  src/components/App/Register/register.js
  src/components/App/SignIn/signIn.js
  src/components/App/StatusForm/statusForm.js
  src/store/actions/cardCheck.js
  src/store/actions/index.js
Labels: toMerge

#41 add jobs users from api to subbcribe form
  src/components/App/Register/register.js
  src/components/App/SignIn/signIn.js
  src/containers/Home/Home.js
  src/services/CaseList.js
  src/services/JobList.js
  src/services/SaveCard.js
  src/store/actions/cardCheck.js
  src/store/actions/index.js
  src/store/actions/registerUser.js
  src/store/reducers/home.js
  src/store/reducers/user.js
Labels: toMerge

#44 Lory entrer button
  src/components/App/Register/register.js
  src/components/App/SignIn/signIn.js
Labels: enhancement, toMerge

#49 sign in css
  src/components/App/Register/register.js
  src/components/App/Register/registerStyle.js
  src/components/App/SignIn/signIn.js
  src/components/App/SignIn/signinStyle.js
  src/components/App/StatusForm/statusForm.js
  src/components/UI/colorTheme/colorTheme.js
  src/images/logo.svg
  src/images/logoteeth_blue.png
  src/images/logoteeth_transparent.png
Labels: toImprove

#52 Design detail case mobile & desktop V1
  src/components/App/DetailCase/cardPlanTreatment.js
  src/components/App/DetailCase/navbarDetail.js
  src/components/App/DetailCase/navbarDetail.scss
  src/components/App/DetailCase/patientDetail.js
  src/components/App/Header/header.js
  src/components/UI/Gallery/gallery.js
  src/containers/DetailCase/detailCase.js
  src/containers/Profile/profile.js
  src/images/empty.png
  src/images/fixtures/carie.jpg
  src/images/fixtures/dent.jpg
  src/images/fixtures/felure.jpg
  src/images/fixtures/plan1.jpg
  src/images/fixtures/plan2.jpg
  src/images/fixtures/plan3.jpg
  src/images/fixtures/radio.jpg
  src/images/fixtures/radio2.jpg
Labels: toMerge

#56 Update the template
  .github/ISSUE_TEMPLATE/1_Bug_Report.md
  .github/ISSUE_TEMPLATE/2_Feature_Request.md
  .github/ISSUE_TEMPLATE/3_Documentation_Issue.md
  .github/ISSUE_TEMPLATE/4_Support_Question.md
Labels: bug

#59 Lory form errors --fixes
  src/components/App/CardForm/cardForm.js
  src/components/App/Cases/Cases.js
  src/components/App/CasesList/CasesList.js
  src/components/App/DetailCase/CardPlanTreatment.js
  src/components/App/DetailCase/NavbarDetail.js
  src/components/App/DetailCase/PatientDetail.js
  src/components/App/DetailCase/cardPlanTreatment.js
  src/components/App/DetailCase/navbarDetail.js
  src/components/App/DetailCase/patientDetail.js
  src/components/App/Header/Header.js
  src/components/App/Register/Register.js
  src/components/App/Register/register.js
  src/components/App/Register/registerStyle.js
  src/components/App/SignIn/SignIn.js
  src/components/App/SignIn/signinStyle.js
  src/components/App/StatusForm/StatusForm.js
  src/components/App/StatusModal/StatusModal.js
  src/components/ResponsiveDesign/AuthStyle.js
  src/components/ResponsiveDesign/ResponsiveCard.js
  src/components/ResponsiveDesign/ResponsiveConstants.js
  src/components/ResponsiveDesign/ResponsiveContainerGrid.js
  src/components/UI/ColorTheme/ColorTheme.js
  src/components/UI/ColorTheme/Palette.js
  src/components/UI/Gallery/Gallery.js
  src/components/UI/Gallery/LightboxButton.js
  src/components/UI/Gallery/gallery.js
  src/components/UI/Gallery/lightboxButton.js
  src/components/UI/Icon/Header/favorites.js
  src/components/UI/Icon/Header/home.js
  src/components/UI/Icon/Header/profile.js
  src/components/UI/Icon/Profile/iconProfile.js
  src/components/UI/Keywords/keywords.js
  src/components/UI/buttons/BlueButton.js
  src/components/UI/buttons/WhiteButton.js
  src/config/index.js
  src/containers/Cases/Cases.js
  src/containers/Cases/cases.js
  src/containers/DetailCase/DetailCase.js
  src/containers/DetailCase/detailCase.js
  src/containers/Favorites/Favorites.js
  src/containers/Home/Home.js
  src/containers/Profile/Profile.js
  src/containers/Profile/profile.js
  src/index.js
  src/services/Cases.js
  src/services/JobList.js
  src/services/Jobs.js
  src/store/actions/cardCheck.js
  src/store/actions/caseItem.js
  src/store/actions/getCases.js
  src/store/actions/index.js
  src/store/reducers/cases.js
  src/store/reducers/home.js
  src/store/reducers/index.js
  src/store/reducers/user.js
  src/utils/fields/checkText.js
Labels: toMerge

#63 fix
  src/components/App/CasesList/CasesList.js
  src/components/App/Register/Register.js
Labels: bug
