Repository DentiioApp/dentiio-front, pull requests merged in 2021-02, with the labels that each got.

#159 update the makefile
  Makefile
Labels: enhancement, toMerge

#160 Deploy preprod front
  .github/workflows/preprod.yaml
Labels: CI / CD, enhancement, toMerge

#167 Comment 'barbe' && used HashLink for anchor && fix date for posted co…
  package.json
  src/components/App/Cases/CaseItem/CaseItem.js
  src/components/App/Cases/Comments/Comments.js
  src/components/App/Cases/DetailCase/NavbarDetail.js
  src/components/App/Cases/DetailCase/PatientDetail.js
  src/containers/UserAvatar/Tab.js
  yarn.lock
Labels: bug

#172 change hour and minutes to 2 digit && sendIcon click
  src/components/App/Cases/Comments/Comments.js
Labels: bug

#164 feature 404 page
  404.html
Labels: bug, enhancement

#175 Lory wainting image
  src/components/App/Cases/PostCase/Omnipratic/Omnipratic.js
  src/store/actions/CasesAction.js
Labels: enhancement, toMerge

#186 Fix notifications repeat
  src/components/App/Auth/SignIn/SignIn.js
  src/components/App/Cases/PostCase/Omnipratic/Omnipratic.js
  src/config/index.js
Labels: toMerge
